import { Scholarship } from "@/components/discover/SwipeCard";

export const MOCK_SCHOLARSHIPS: Scholarship[] = [
  {
    id: "1",
    provider_name: "Google",
    title: "Women Techmakers Scholarship",
    amount: 10000,
    deadline_days: 12,
    win_probability: 45,
    effort_hours: 3,
    tags: ["STEM", "Women", "Undergrad"],
    description: "For women studying computer science or a related field. Essay required about your impact on the community.",
    color_start: "from-blue-500",
    color_end: "to-blue-700",
  },
  {
    id: "2",
    provider_name: "Thiel",
    title: "Thiel Fellowship",
    amount: 100000,
    deadline_days: 45,
    win_probability: 2,
    effort_hours: 15,
    tags: ["Entrepreneurship", "Dropout", "Tech"],
    description: "For young people who want to build new things instead of sitting in a classroom.",
    color_start: "from-orange-400",
    color_end: "to-rose-500",
  },
  {
    id: "3",
    provider_name: "Taco Bell",
    title: "Live Más Scholarship",
    amount: 25000,
    deadline_days: 5,
    win_probability: 12,
    effort_hours: 1,
    tags: ["Video", "Creative", "No-Essay"],
    description: "Create a 2-minute video about your passion. No grades or essays required.",
    color_start: "from-purple-600",
    color_end: "to-indigo-900",
  },
  {
    id: "4",
    provider_name: "Burger King",
    title: "Burger King Scholars",
    amount: 1000,
    deadline_days: 28,
    win_probability: 65,
    effort_hours: 2,
    tags: ["High School", "GPA 2.5+", "Community"],
    description: "For high school seniors with a strong academic record and community service experience.",
    color_start: "from-amber-500",
    color_end: "to-amber-700",
  },
  {
    id: "5",
    provider_name: "Gates",
    title: "The Gates Scholarship",
    amount: 50000, // Full ride
    deadline_days: 120,
    win_probability: 5,
    effort_hours: 20,
    tags: ["Minority", "Low-Income", "Leadership"],
    description: "A highly selective, last-dollar scholarship for outstanding minority students.",
    color_start: "from-slate-700",
    color_end: "to-slate-900",
  }
];
